import type { Opportunity } from "../shared/schema";

export const seedOpportunities: Opportunity[] = [
  {
    id: "seed-1",
    title: "Founding Product Intern",
    company: "Northstar Labs",
    companyWebsite: "https://example.com/northstar-labs",
    location: "Bengaluru, India",
    summary:
      "Work directly with the founding team on product discovery, user interviews, and go-to-market experiments for an early-stage AI tooling startup.",
    employmentType: "Internship",
    track: "internship",
    tags: ["Product", "Startup", "AI", "Founding Team"],
    compensation: "Stipend disclosed during interview",
    remote: true,
    visaSponsorship: false,
    startup: true,
    startupScore: 88,
    source: "seed",
    sourceUrl: "https://example.com/northstar-labs/jobs/founding-product-intern",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-2",
    title: "Research Engineer, Applied ML",
    company: "Open Frontier Research",
    companyWebsite: "https://example.com/open-frontier-research",
    location: "Remote",
    summary:
      "Build evaluation pipelines, fine-tune open models, and support experimental research work in retrieval and agent systems.",
    employmentType: "Full-time",
    track: "research",
    tags: ["Research", "ML", "LLM", "Python"],
    compensation: "Competitive salary",
    remote: true,
    visaSponsorship: true,
    startup: false,
    startupScore: 42,
    source: "seed",
    sourceUrl: "https://example.com/open-frontier-research/jobs/research-engineer",
    postedAt: new Date().toISOString(),
    researchDomain: "Applied machine learning",
  },
  {
    id: "seed-3",
    title: "Software Engineer",
    company: "Atlas Commerce",
    companyWebsite: "https://example.com/atlas-commerce",
    location: "Pune, India",
    summary:
      "Ship full-stack product features across React, Node.js, and PostgreSQL in a fast-moving commerce platform.",
    employmentType: "Full-time",
    track: "full-time",
    tags: ["React", "Node.js", "PostgreSQL"],
    compensation: "Salary based on experience",
    remote: false,
    visaSponsorship: false,
    startup: false,
    startupScore: 24,
    source: "seed",
    sourceUrl: "https://example.com/atlas-commerce/jobs/software-engineer",
    postedAt: new Date().toISOString(),
  },
];
